### ISSUE TITLE
MIDS element - RecordCreator

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#13]
|  |  |
| ---- | ---- |
| **MIDS information element** | RecordCreator |
| **Definition** | |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Agreed to delete from specification* |
| ***Notes*** | *...* |

**Comment by hardistyar** [comment]
2nd TG, 202101-07 noted that, although such data (creation date, modified date and person making the change) is normally available internally in database systems, it's presence publicly at each MIDS level is probably not very useful. Of the three pieces of information, the date/time on which the data was most recently modified is the most useful. There are discovery use cases, for example where someone might want to know about all date created or modified since a particular moment. Note that the first date given in a Modified information element is most likely the creation date anyway.
The proposal is to drop CreatedOn and RecordCreator and to retain Modified.
See also #7 and #8.

**Comment by hardistyar** [comment]
TDWG TG 3 meeting on 4th February 2021 agreed to remove this information element from the definition at all MIDS levels.

**Comment by hardistyar** [comment]
Element removed in v0.14 of the working draft specification text, 29th March 2021.
