### ISSUE TITLE
What should be the basis of MIDS terms - Darwin Core or ABCD-EFG?

### ISSUE THREAD

**Issue by hardistyar** [tdwg/mids#41]
What should be the basis of MIDS terms - Darwin Core terms or ABCD-EFG terms or a common aligned term?

example: We want to include the date of gathering of a specimen. Presently this is suggested as collectionDate. See #24. But it could be eventDate from DwC or Date from ABCD.

We can define new terms and equivalence them to both DwC and ABCD, or we can pick by preferring DwC over ABCD or vice-versa. If we prefer DwC, that only works so far. Once we get to geological terms Darwin Core breaks down and ABCD-EFG becomes the only source.

How will the alignment work solve this issue? And how will the semantic equivalencing be achieved? Will there be a machine-readable thesaurus?

Perhaps @DavidFichtmueller and @matdillen has an opinion?

**Comment by matdillen** [comment]
Maybe we should use either of the two and not mint any new labels ourselves? What is currently `mids:collectionDate`, would be `dwc:eventDate` **or** `abcd:Gathering/Date`. If there are properties that are only supported by one of the two standards, that is a problem, but then at least the term of that standard could be used?

**Comment by dagendresen** [comment]
I think it would be more useful to try to reuse terms declared in Darwin Core and ABCD (both TDWG standards). Because GBIF primarily uses Darwin Core, I suggest considering looking for a term in Darwin Core first? I believe that minting new terms in MIDS (?) would only cause MIDS to be less useful. And that if the need for new terms is identified, rather try to propose such terms for Darwin Core or ABCD.

**Comment by emhaston** [comment]
DWC and ABCD will both be incorporated into the MIDS mapping
