### ISSUE TITLE
Why must a digital specimen be on the Internet

### ISSUE THREAD

**Issue by smrgeoinfo** [tdwg/mids#43]
The draft (abstract, introduction) states that a digital specimen is a digital representations on the Internet (or 'online').  This seems like an unnecessary restriction.  The model is perfectly valid for representing specimen in any information system, online or offline.

**Comment by hardistyar** [comment]
The principal focus of MIDS is on the minimum to be made available when publishing digital specimen information. Publishing in this sense is generally taken to mean publishing openly on the Internet i.e., online. Since offline systems are not usually publicly available they are therefore not in scope.

MIDS is a minimal common data model for making a minimum amount of useful information available publicly. As such it is not intended to be a complete specification of the Digital Specimen model. That comprehensive data model will be provided by the [openDS (open Digital Specimen) specification](https://github.com/DiSSCo/openDS), with which MIDS is fully compatible but like MIDS this is a specification that applies at the interfaces of systems, not to the internals of systems. Whether such specifications are followed internally is a matter of design, with choices dictated by many factors.

A [Digital Specimen](https://dissco.tech/2020/03/31/what-is-a-digital-specimen/) is a precisely defined kind of [FAIR Digital Object (FDO)](https://fairdo.org/) - with specific characteristics - that exists in an online (Internet) world.

The specific characteristics of Digital Specimens include: i) being identified by a persistent identifier, such as a DOI; ii) having a clear type definition such that they can be processed by computers interoperably and reusably; iii) having (meta)data describing what the physical specimen is and where it came from (=the content of MIDS but more than that as well, in order to make them FAIR); iv) allowing for defined operations associated with them that can be invoked remotely using a standard protocol - preferably [Digital Object Interface Protocol (DOIP)](https://www.dona.net/sites/default/files/2018-11/DOIPv2Spec_1.pdf) but HTTP also possible; and v) having a standard serialization form (JSON).
