### ISSUE TITLE
Mapping template for MIDS level 1

### ISSUE THREAD

**Issue by hardistyar** [tdwg/mids#49]
Design and agree mapping template for mapping institutional collection management and other data management schema terms/fields to MIDS level 1 information elements.

**Comment by hardistyar** [comment]
Elspeth (RGBE) has provided one: https://docs.google.com/spreadsheets/d/1pvEdHjbZdfCs26a_Q71UzZCtpJtzVIcMtxv8FtJA-Fs/edit?usp=sharing

**Comment by emhaston** [comment]
Mapping of MIDS-1 elements

- [ ] Modification
- [ ] PhysicalSpecimenIdentifier
- [ ]

**Comment by cp-weiland** [comment]
Some matching terms I found, organization has an exact match in ABCD (I think), we might fit MIDS level in openDS (which has a narrower def), dcterms modified/license are in DWC - maybe that fits also for MIDS? 

MIDS term | Mapping Label | Mapping URI | used in DWC?
-- | -- | -- | --
Modified | Date Modified | http://purl.org/dc/terms/modified | yes, same
PhysicalSpecimenId | Maps broadly to: dwc:catalogNumber, dwc:occurrenceID, dwc:materialSampleID, ABCD:physicalObjectID |   | yes, DWC/ABCD
Organisation | Organisational Unit Name (LC) Organization (ABCD) | https://github.com/tdwg/cd/issues/198   http://rs.tdwg.org/abcd/terms/Organization |  no, but in ABCD
SpecimenType | dwc:materialSampleType |   | proposed?  
ObjectType | Broadly maps to: dwc:preparations, ABCD:kindOfUnit |   |  
Name | dcterms:title   |  http://purl.org/dc/terms/title  | no, also not in ABCD
Licence | License | http://purl.org/dc/terms/license | yes, same
MIDSLevel | MIDS Level | https://modelling.dissco.tech/wiki/Item:Q18 | ,no, skos:broadMatch to ods:MIDSLevel


</body>

</html>

**Comment by matdillen** [comment]
Both openDS and ongoing developments in TDWG task groups for Darwin Core are currently still moving targets with no effective implementations yet and hence no GBIF support. We used Darwin Core as it is used as of now, because it is already widely implemented and available, hence it can be utilized for immediate MIDS calculations. 

The mappings are not perfect, as Darwin Core is not either and MIDS itself is still being developed, but dwc:basisOfRecord is the best approximation we have now for specimenType. Mineral names are currently not in scope of this schema. We would probably need a different one to accommodate such specimens. Mappings to ABCD may be useful in this regard, but we'd have to develop them and I lack experience with that standard to make that happen efficiently.

**Comment by emhaston** [comment]
This has been superceded by other mapping issue versions
