### ISSUE TITLE
MIDS Element - CreatedOn

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#7]
|  |  |
| ---- | ---- |
| **MIDS information element** | CreatedOn |
| **Definition** | UTC date/time of record creation |
| **DwC term (latest, 2014-11-08)** | No equivalent |
| **ABCD term name(3.0)** | hasDateCreated |
| **Applicable standard(s)/recommendation(s) | Use [ISO 8601](https://www.iso.org/standard/70907.html). UTC date/time, extended format (for human readability) |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** | 2021-01-20T10:54:18Z |
| ***Element specification status*** | *Agreed to delete from specification* |
| ***Relevant notes*** | *...* |

**Comment by RBGE-Herbarium** [comment]
Low percentage of preserved specimen occurrences in GBIF have data for this, but it is likely that most CMS instances would hold the data.
Would therefore not necessarily be a barrier.
Should we be encouraging submission of this information to GBIF? Why are institutes not submitting these data at the moment?
Need use cases.

**Comment by matdillen** [comment]
There is no Darwin Core term for this property, so it is not supported by the IPT. I'm not sure how these data could be submitted to GBIF at the moment?

What is the definition of 'creation' in this context?

**Comment by hardistyar** [comment]
2nd TG, 202101-07 noted that, although such data (creation date, modified date and person making the change) is normally available internally in database systems, it's presence publicly at each MIDS level is probably not very useful. Of the three pieces of information, the date/time on which the data was most recently modified is the most useful. There are discovery use cases, for example where someone might want to know about all date created or modified since a particular moment. Note that the first date given in a Modified information element is most likely the creation date anyway.
The proposal is to drop CreatedOn and RecordCreator and to retain Modified.
See also #8 and #13.

**Comment by hardistyar** [comment]
TDWG TG 3 meeting on 4th February 2021 agreed to remove this information element from the definition.

**Comment by hardistyar** [comment]
Element removed in v0.14 of the working draft specification text, 29th March 2021.
